JackSkiles/BThree

- client/package-lock.json
- client/package.json
- client/src/App.js
Just got started on route creation and some components.
> updated some styling and routes

- client/src/App.js
- client/src/pages/register.jsx
hey, guys, i created a register form/page . please take a look.
> created register form

- client/src/App.js
- client/src/pages/login.jsx
hey created a quick login form
> created a login page

- app.js
- bin/www
- client/src/App.js
- package-lock.json
- package.json
- routes/api.js
Added database features that should help us in creating a database.
> updated database features

- client/.gitignore
- client/package-lock.json
- client/package.json
- client/send_sms.js
- package-lock.json
Added the file for Twilio and it's working. .env file with the credentials is in Slack
> twilio basics functioning

- config/config.json
- migrations/20200708175627-create-users.js
- migrations/20200708180539-create-emergency-contacts.js
- migrations/20200708180623-create-users-to-emergencycontacts.js
- models/emergencycontacts.js
- models/users.js
> adds migrations and models

- bin/www
- client/src/App.js
- config/config.json
- package-lock.json
- package.json
Added in some voice recognition stuff.
> Added browser voice command functionality

- client/src/App.js
- client/src/pages/feed.css
- client/src/pages/feed.jsx
> rough draft for feed page

- migrations/20200708175627-create-users.js
- migrations/20200708180539-create-emergency-contacts.js
- seeders/20200709133644-users.js
- seeders/20200709133733-emergencycontacts.js
> adds seeders

- package-lock.json
- routes/sms.js
This connects the DB to the post request for sending text messages
> twilio pulling from emergency contact DB

- client/src/App.js
Should work most of the time. If it is throwing to many errors feel free to comment out the whole use effect  method/hook. Going to keep working on bug fixing.
> got the voice control beta working.

- client/src/App.js
- client/src/pages/login.jsx
- client/src/pages/register.jsx
Hopefully fixed the voice control bugs
> More voice work/jack skiles

- client/src/App.js
- client/src/pages/register.jsx
> App.js fixes/jack skiles

- routes/api.js
adds delete user, emergency contact, and update emergency contact routes
> Expressrouting

- client/package.json
- client/src/App.js
- client/src/component/PanicButton.jsx
- client/src/component/PanicButton.module.css
- client/src/pages/login.jsx
- routes/sms.js
The button is created and working but there's not a reference to the DB yet.
> functioning panic button w/o DB pull

- client/src/App.js
> fixed voice bug

- client/public/index.html
- client/src/App.js
- client/src/component/LandingPage.jsx
- client/src/component/emergencyContacts.css
- client/src/component/emergencyContacts.jsx
- client/src/pages/account.css
- client/src/pages/account.jsx
added some styling to account page
> added some styling mainly to account page

- routes/sms.js
Twilio post now sending message to contacts from DB. Hardcoded to user 6 for now.
> Contacts/Message coming from DB

- app.js
- auth/checkAuthentication.js
- client/src/App.js
- client/src/component/navbar.jsx
- client/src/pages/account.jsx
- client/src/pages/login.jsx
- routes/api.js
> More auth/jack skiles

- client/src/component/Map.js
- client/src/pages/contacts.js
- client/src/pages/register.jsx
- routes/api.js
Wes and I fixed the contacts so all of the contacts go to the database when submitted and user is logged in.
> all contacts go to the database now

- client/src/pages/account.css
- client/src/pages/account.jsx
> made formatting changes to git file

- client/src/pages/about.jsx
We can change the wording on any of this! Consolidating this page.
> aboutpagemods

- README.md
Adding a the README. May need edits after team review.
> Readmecreation
